version: "3"
services:
  iotanode:
    image: iotanode:lastest
    build:
      context: .
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
      restart_policy:
        condition: on-failure
    networks:
      - iotaswarm

networks:
  iotaswarm:

